### ISSUE TITLE
Task list : Basic functionality 

### ISSUE THREAD

**Issue by Jasja1231** [Jasja1231/Mind_Sweeper_Game#1]
- [x] In the Minesweeper game player has to discover all fields without mines. Numbers are hint, where the mines are.
- [x] The upper part of the window: menu File - allowing to start the game or exit an application,
- [x] Options - allowing to set board size and number of mines
- [x] The bottom part of the window: status strip - number of mines which are not flagged
- [x] The rest of the window: the game board
- [x] After starting new game a form is resized so that buttons are of size 60x60.
- [x] Size of the board is set to 4 by 4 unless changed in the options dialog
- [x] One can assume that in the options dialog only correct numbers are inserted
- [x] Arrangement of mines randomized with each start of the game
- [x] Undiscovered field - the appearance of a standard button without text
- [x] One can click on a field with left or right button. Left button makes button disappear and creates label with number (if there is no mine on the field) or red label with text "MINE". 
- [x] Right button "flag" button and it cannot be clicked with left button until "unflagged" again with right button.
- [x] Uncovering field with mine should display message with "Game over" text, from this moment it is not possible to keep playing (board game becomes inactive)
- [x] Uncovering all fields without mines should display a congratulation message.
- [x] Option Exit from menu File should display window with confirmation.
- [x] Proper handling resize the window (as in example applications)
- [x] Label after discovering field should have Font "Microsoft Sans Serif", size 6 for mine and 10 otherwise. 
- [x] Text align should be in the middle and centered.
