### ISSUE TITLE
Task list : Additional  functionality 

### ISSUE THREAD

**Issue by Jasja1231** [Jasja1231/Mind_Sweeper_Game#2]
- [x] Only the main application window visible in the taskbar
- [ ]  When user clicks on a field surrounded by 0 mines, label text should be empty and all surrounding fields should be discovered recursively.
- [x] Game timer: time of a game should be displayed in a right bottom part, in a status strip.
- [x] Highscores: Separate window in which top 10 players are listed. Highscores should be sorted by time.
- [x] Options: Separate window in which difficulty level can be chosen as well as name of player (visible in highscores). 
             -Level Beginner: 4x6, 1 mine. 
             -Intermediate: 8x8, 12 mines. 
             -Hard: 10x10, 50 mines
- [x]  Not standard level should be validated: width and height are integers from [1,15] interval, number of mines is from 0 to width*height. If not proper values are provided, the message should be displayed. In this part one can not assume that entered text is correct number
  Highlighting in proper color the button, on which mouse entered (Color.OrangeRed, SystemColors.ActiveCaption, SystemColors.Control, Color.Red)
